package com.example.multithreadeddownload.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.multithreadeddownload.bean.GreenDaoBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_DAO_BEAN".
*/
public class GreenDaoBeanDao extends AbstractDao<GreenDaoBean, Long> {

    public static final String TABLENAME = "GREEN_DAO_BEAN";

    /**
     * Properties of entity GreenDaoBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Thread_id = new Property(1, Integer.class, "thread_id", false, "THREAD_ID");
        public final static Property Start_pos = new Property(2, Integer.class, "start_pos", false, "START_POS");
        public final static Property End_pos = new Property(3, Integer.class, "end_pos", false, "END_POS");
        public final static Property Complete_size = new Property(4, Integer.class, "complete_size", false, "COMPLETE_SIZE");
        public final static Property Url = new Property(5, String.class, "url", false, "URL");
    }

    private DaoSession daoSession;


    public GreenDaoBeanDao(DaoConfig config) {
        super(config);
    }
    
    public GreenDaoBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_DAO_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"THREAD_ID\" INTEGER," + // 1: thread_id
                "\"START_POS\" INTEGER," + // 2: start_pos
                "\"END_POS\" INTEGER," + // 3: end_pos
                "\"COMPLETE_SIZE\" INTEGER," + // 4: complete_size
                "\"URL\" TEXT);"); // 5: url
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_DAO_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GreenDaoBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer thread_id = entity.getThread_id();
        if (thread_id != null) {
            stmt.bindLong(2, thread_id);
        }
 
        Integer start_pos = entity.getStart_pos();
        if (start_pos != null) {
            stmt.bindLong(3, start_pos);
        }
 
        Integer end_pos = entity.getEnd_pos();
        if (end_pos != null) {
            stmt.bindLong(4, end_pos);
        }
 
        Integer complete_size = entity.getComplete_size();
        if (complete_size != null) {
            stmt.bindLong(5, complete_size);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(6, url);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GreenDaoBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer thread_id = entity.getThread_id();
        if (thread_id != null) {
            stmt.bindLong(2, thread_id);
        }
 
        Integer start_pos = entity.getStart_pos();
        if (start_pos != null) {
            stmt.bindLong(3, start_pos);
        }
 
        Integer end_pos = entity.getEnd_pos();
        if (end_pos != null) {
            stmt.bindLong(4, end_pos);
        }
 
        Integer complete_size = entity.getComplete_size();
        if (complete_size != null) {
            stmt.bindLong(5, complete_size);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(6, url);
        }
    }

    @Override
    protected final void attachEntity(GreenDaoBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GreenDaoBean readEntity(Cursor cursor, int offset) {
        GreenDaoBean entity = new GreenDaoBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // thread_id
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // start_pos
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // end_pos
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // complete_size
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // url
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GreenDaoBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setThread_id(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setStart_pos(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setEnd_pos(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setComplete_size(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GreenDaoBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GreenDaoBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GreenDaoBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
